on:
  schedule:
    - cron:  '*/3 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
          with:
            repository: liferay-latam/liferay-portal
#             token: ${{ secrets.PAT_TOKEN }}
        - run: git remote add upstream https://github.com/liferay/liferay-portal.git
        - run: git fetch upstream
        - name: Sync master
          run: git push origin upstream/master:master
          env:
            repo-token: ${{ secrets.PAT_TOKEN }}
