on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
          with:
            name: liferay-latam/liferay-portal
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Sync master
          run: git push origin upstream/master:master
